services:
  db:
    image: mysql:8.0
    container_name: mysql_horarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sscd_horarios
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db_data:


